### ISSUE TITLE
Decrypt encrypted secret key.

### ISSUE THREAD

**Issue by CB2017** [future-tense/stargazer#47]
Hi,

I have the QR of the encrypted key and the password used to generate the key. Is there any way I can decrypt the key and get my 'real' secret key?
Thanks.

**Comment by kfiresmith** [comment]
What platform are you on?  Do you have access to a Linux host?

**Comment by CB2017** [comment]
Thanks for the reply. I'm normally on a Windows machine but I do have access to a Linux VM.

**Comment by kfiresmith** [comment]
I've played around with the Linux 'openssl' command trying to decrypt the last string of an encrypted export  and come up short.  I'm hoping @johansten might have some advice for taking the text of an encrypted keypair export and decoding it with your password.  

This is assuming you no longer have the machine you originally ran Stargazer on, right?  Because if you still have that machine you should be able to re-open Stargazer and it will show the account in question, which you could then decrypt (remove password protection) from, which would provide a plaintext secret when you scan the QR.

Sorry about this!

**Comment by CB2017** [comment]
Thanks for taking a look.

So the full story is that something happened to my installation of Stargazer and the account has disappeared from the program. There is a backup or cached file on the PC that I can dig out and recover the account?

**Comment by johansten** [comment]
If you have the QR code for exporting accounts, can't you just *import* it in a new installation?

**Comment by rathfon** [comment]
I'm having the same issue - didn't "unlock" my wallet before exporting the QR code. I have the encrypted version of it so pulling the QRCode data doesn't do me any good. I can't import the QR code into it because of the encryption and stargazer doesn't take it's own QRcodes (desktop ver) to be able to unecrypt them. Anyone have an idea?

**Comment by johansten** [comment]
@rathfon

Not recognizing its own QR codes isn't something I've heard before :/

 Here's something I wrote for someone with a similar situation, https://gist.github.com/johansten/35f4767e2f1d4d108a4bb21ff8289ec7

It's a bit technical, and you'll need to make sure you have node and npm installed before you do it.

**Comment by rathfon** [comment]
I'm sorry, I didn't mean to make it seem like the QRcode wasn't readable. I meant extracting the QRCode into raw text obviously doesn't do me much good.

I have various android phones I've tried pulling the encrypted QRcode into - that's its use correct, for that type of lateral movement? The app doesn't open unfortunately on the older one, and the next one it reads the QR and then white screens for an infinite loop.

Thank you for responding - I didn't realize I was hassling the dev's personally about this. I seemingly had a drive crash and my physical kept of the seed was destroyed so I'm left with just the encrypted QR code. 

I'll try to give what you linked a shot, I'm fairly familiar with some light js but not accompanied by node and npm. Hopefully I can just get an android phone that actually seems to work

Thank you again! you're awesome

**Comment by INJprotocol** [comment]
Hello, i am having the same issue and I’ve tried all channel to try to resolve but not possible.

I have the QR restore code (did not had password on my wallet).
Formatted my macbook.
Downloaded latest stargazer wallet and scanned the QR code for import but does not work.

Decoded the QR code on website https://zxing.org/w/decode.jspx

Result in this format as QR encrypted : {"stellar":{"account":{"network":"7ac33997"},"key":["1","QORedgZKB45ASAX1J5H5OQ==",["3inmOuWxWdOvQ/bo","J2Um44t+H6au99xbkvnvU2CFGC43wj65apeF+BMdn1COjP7yU2knKv7Zbj2GbklTLm5nio1BbcCsywlJHz3Uhlhf5mMQWpst"]]}}

My question is how do i Décrypt the result : {"stellar":{"account":{"network":"7ac33997"},"key":["1","QORedgZKB45ASAX1J5H5OQ==",["3inmOuWxWdOvQ/bo","J2Um44t+H6au99xbkvnvU2CFGC43wj65apeF+BMdn1COjP7yU2knKv7Zbj2GbklTLm5nio1BbcCsywlJHz3Uhlhf5mMQWpst"]]}}
?

Hope i was clear enough.
